/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Repositorio.Repositorio;


/**
 *
 * @author -
 */
public class TelaSaldo extends javax.swing.JFrame {

    /**
     * Creates new form TelaSaldo
     */
    public TelaSaldo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        botaoVoltar = new javax.swing.JButton();
        labelValorSaldo2 = new javax.swing.JLabel();
        textSaldo = new javax.swing.JTextField();
        labelValorSaldo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SALDO");
        setMaximumSize(new java.awt.Dimension(450, 350));
        setMinimumSize(new java.awt.Dimension(450, 350));
        getContentPane().setLayout(null);

        botaoVoltar.setBackground(new java.awt.Color(0, 0, 0));
        botaoVoltar.setForeground(new java.awt.Color(255, 255, 255));
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoVoltar);
        botaoVoltar.setBounds(170, 260, 100, 40);

        labelValorSaldo2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelValorSaldo2.setForeground(new java.awt.Color(0, 0, 0));
        labelValorSaldo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelValorSaldo2.setText("R$:");
        labelValorSaldo2.setToolTipText("");
        labelValorSaldo2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                labelValorSaldo2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(labelValorSaldo2);
        labelValorSaldo2.setBounds(150, 150, 30, 20);

        textSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSaldoActionPerformed(evt);
            }
        });
        getContentPane().add(textSaldo);
        textSaldo.setBounds(431, 362, 10, 0);

        labelValorSaldo.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        labelValorSaldo.setForeground(new java.awt.Color(0, 0, 0));
        labelValorSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelValorSaldo.setText("Saldo");
        labelValorSaldo.setToolTipText("");
        labelValorSaldo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                labelValorSaldoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(labelValorSaldo);
        labelValorSaldo.setBounds(140, 130, 160, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\-\\Pictures\\Cofin\\Saldo.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 10, 230, 230);

        jPanel1.setBackground(new java.awt.Color(60, 63, 66));
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 440, 370);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        this.dispose();
        new TelaPrincipal().setVisible(true);
    }                                           

    private void textSaldoActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    // TESTE    String saldo = textSaldo.getText(Float.toString(Repositorio.Saldo()));
    //    String saldo = Repositorio.SaldoString(); NÃO DEU NENHUM JEITO
    //    textSaldo.setText(SaldoString());
    }                                         

    private void labelValorSaldoAncestorAdded(javax.swing.event.AncestorEvent evt) {                                              
        // TODO add your handling code here:
        Repositorio repositorio = new Repositorio();
        String saldo = repositorio.saldoString();
        labelValorSaldo.setText(saldo);
        
    }                                             

    private void labelValorSaldo2AncestorAdded(javax.swing.event.AncestorEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSaldo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelValorSaldo;
    private javax.swing.JLabel labelValorSaldo2;
    private javax.swing.JTextField textSaldo;
    // End of variables declaration                   
}
