/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import com.mycompany.cofin.OperacaoSaida;
import javax.swing.JOptionPane;

/**
 *
 * @author -
 */
public class TelaSaida extends javax.swing.JFrame {

    /**
     * Creates new form TelaSaida
     */
    public TelaSaida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        textValor = new javax.swing.JTextField();
        textNome = new javax.swing.JTextField();
        botaoSalvar = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DESPESA");
        setMaximumSize(new java.awt.Dimension(450, 350));
        setMinimumSize(new java.awt.Dimension(450, 350));
        getContentPane().setLayout(null);

        textValor.setBackground(new java.awt.Color(255, 255, 255));
        textValor.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(textValor);
        textValor.setBounds(50, 170, 270, 40);

        textNome.setBackground(new java.awt.Color(255, 255, 255));
        textNome.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(textNome);
        textNome.setBounds(50, 70, 270, 40);

        botaoSalvar.setBackground(new java.awt.Color(255, 255, 255));
        botaoSalvar.setForeground(new java.awt.Color(0, 0, 0));
        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoSalvar);
        botaoSalvar.setBounds(220, 240, 100, 40);

        botaoVoltar.setBackground(new java.awt.Color(0, 0, 0));
        botaoVoltar.setForeground(new java.awt.Color(255, 255, 255));
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoVoltar);
        botaoVoltar.setBounds(50, 240, 100, 40);

        jPanel1.setBackground(new java.awt.Color(60, 63, 66));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\-\\Pictures\\Cofin\\Despesa.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(320, 82, 100, 100);

        jLabel4.setBackground(new java.awt.Color(255, 206, 236));
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nome");
        jLabel4.setToolTipText("");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 30, 100, 40);

        jLabel3.setBackground(new java.awt.Color(255, 206, 236));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Valor");
        jLabel3.setToolTipText("");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 130, 100, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 480, 330);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        this.dispose();
        new TelaPrincipal().setVisible(true);
    }                                           

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        String nome = this.textNome.getText();
        String valor = this.textValor.getText();
        
        if (nome.isEmpty() || valor.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Verifique se a o Nome e o Valor estão devidamente preenchidos.", "Eu CONFINei em você", JOptionPane.WARNING_MESSAGE);
                
            }else if (!isNumero (valor)){
                JOptionPane.showMessageDialog(null, "O Valor deve ser um número válido.", "Eu CONFINei em você", JOptionPane.WARNING_MESSAGE);
        
                }else{ 
        
        OperacaoSaida saida = new OperacaoSaida();
        saida.setNome(nome);
        saida.setValor(Float.parseFloat(valor));
        
        Repositorio.Repositorio.saidas.add(saida);
        System.out.println(Repositorio.Repositorio.somaDespesa());
        
        this.textNome.setText("");
        this.textValor.setText("");
        
        }
    }                                           

    private boolean isNumero (String valor) {
        try {
            Float.parseFloat(valor);
            return true;
        } catch (NumberFormatException e){
            return false;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSaida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textValor;
    // End of variables declaration                   
}
